<a href="https://colab.research.google.com/github/anilans029/PyTorch/blob/main/PyTorch_basic_overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

### **Tensors in PyTorch**

> whenever we work with deep learning models there will be lot of computations required and with cpu the speed will be very slow. So, utilize the GPU we need to give everything in the form of tensors. 

> since the gpu have a lot of cores, we can achieve parallel computation and speed of training is very high when compared to cpu

> in the list we can mention multiple data types at once but in tensors we cant define multiple data type values at once

> suppose if we are having 1 float value and remaining ara the integers then tensor will convert all of them into float values

In [7]:
t1 = torch.tensor(4.)
t1

tensor(4.)

> we are giving the numbers in the float type because we know during the backtracking or gradients calculating, the weights get updated and will be in the float types

In [8]:
type([4]), type(t1)

(list, torch.Tensor)

In [9]:
t1.dtype

torch.float32

## **Vector**

vector = list of numbers

matrix = list of list of numbers

In [18]:
t2 = torch.tensor([1., 2.,3.,4.])

## **Matrix**

In [10]:
t3 = torch.tensor(
    [
        [1.,2.,3.],
     [3.,4.,11]
    ]
)

t3

tensor([[ 1.,  2.,  3.],
        [ 3.,  4., 11.]])

In [11]:
### 3-D array or tensor

t4 = torch.tensor([
                  [[1.,2.,3.],
                  [4.,5.,6.]],

                  [[11.,22.,33],
                  [12.,44.,56]]
                  ]
    )
t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[11., 22., 33.],
         [12., 44., 56.]]])

In [23]:
t1.shape, t2.dtype

(torch.Size([]), torch.float32)

In [22]:
t2.shape, t2.dtype

(torch.Size([4]), torch.float32)

In [24]:
t3.shape, t2.dtype

(torch.Size([2, 3]), torch.float32)

In [25]:
t4.shape, t2.dtype

(torch.Size([2, 2, 3]), torch.float32)

# **Tensors Opereations**

PyTorch suports auto grad operation i.e calculating the gradient autmatically

> but how it knows for which parameters it need to do auto gradient i.e, which are trainable parameters

> for that we need to metion requires_grad = true::

In [27]:
x = torch.tensor(2.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(4., requires_grad = True)

In [28]:
## Arithmetic 

y = w*x + b
y

tensor(12., grad_fn=<AddBackward0>)

In [29]:
## to calculate the gradients 

y.backward()

In [31]:
print("dy/dx", x.grad)
print("dy/dw", w.grad)
print("dy/db", b.grad)

dy/dx None
dy/dw tensor(2.)
dy/db tensor(1.)


## **Tensor functions**

In [32]:
## create a full array with same value

t6 = torch.full((3,3), 22)
t6

tensor([[22, 22, 22],
        [22, 22, 22],
        [22, 22, 22]])

In [34]:
## to concatenate two tensors

t7 = torch.cat((t3,t6))
t7

tensor([[ 1.,  2.,  3.],
        [ 3.,  4., 11.],
        [22., 22., 22.],
        [22., 22., 22.],
        [22., 22., 22.]])

In [35]:
## sin value of all the values in tensor

t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411],
        [ 0.1411, -0.7568, -1.0000],
        [-0.0089, -0.0089, -0.0089],
        [-0.0089, -0.0089, -0.0089],
        [-0.0089, -0.0089, -0.0089]])

In [36]:
## reshape the tensors

t9 = t8.reshape(3,5)
t9

tensor([[ 0.8415,  0.9093,  0.1411,  0.1411, -0.7568],
        [-1.0000, -0.0089, -0.0089, -0.0089, -0.0089],
        [-0.0089, -0.0089, -0.0089, -0.0089, -0.0089]])

## ***Interoperability with numpy***

> generally we need tensors when we are giving our parameters for training

> but before giving to training, we can work with numpy

1. converting the numpy into tensor

In [39]:
import numpy as np

x = np.array([[22, 22, 22],
              [22, 22, 22],
              [22, 22, 22]])

y = torch.from_numpy(x)
y


tensor([[22, 22, 22],
        [22, 22, 22],
        [22, 22, 22]])

2. converting tensor to numpy

In [40]:
y.numpy()

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])